# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: F7C3B4A2-8E9D-4F6A-A1B7-2C5D8E9F0123
publisher: Lightbridge-KS
publisher_url: https://github.com/Lightbridge-KS/designcter
display_name: DesignCTER
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en