project:
  type: book

book:
  title: "DesignCTER"
  subtitle: "A User Guide"
  author: "Kittpos Sirivongrungson"
  repo-url: https://github.com/Lightbridge-KS/designCTER
  sidebar: 
    background: "#F5F5F5"
    logo: "img/DesignCTER-2.5.png"
    search: true
  downloads: [docx]
  date: today
  chapters:
    - index.md
    - protocols-basic.md
    - protocols-docs.qmd
    - reference.qmd

format: 
  html: 
    toc: true
    toc-depth: 3
    theme: simplex # lux
  docx:
    reference-doc: "assets/proprosal-ref-v2.docx"
    link-bibliography: true
    link-citations: true

bibliography: "assets/reference.bib"
csl: "assets/elsevier-with-titles.csl"

freeze: auto

